spring:
  cloud:
    streamapp:
      security:
        enabled: false
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-1
    credentials:
        accessKey:
        secretKey:
