//tag::ref-doc[]
= HttpGateway Processor

A processor application that proxies HTTP requests to Httpclient Gateway Processor and returns responses back.
If the Content-Type matches `text/*` or `application/json`, the payload will be a String,
otherwise the payload will be a byte array.

== Input
//TODO
=== Headers
//TODO
=== Payload
//TODO
== Output
//TODO
=== Headers
//TODO
=== Payload
//end::ref-doc[]

== Options

The **$$http-gateway$$** $$processor$$ has the following options:

//tag::configuration-properties[]
$$http-gateway.cors.allow-credentials$$:: $$Whether the browser should include any cookies associated with the domain of the request being annotated.$$ *($$Boolean$$, default: `$$<none>$$`)*
$$http-gateway.cors.allowed-headers$$:: $$List of request headers that can be used during the actual request.$$ *($$String[]$$, default: `$$<none>$$`)*
$$http-gateway.cors.allowed-origins$$:: $$List of allowed origins, e.g. "https://domain1.com".$$ *($$String[]$$, default: `$$<none>$$`)*
$$http-gateway.mapped-request-headers$$:: $$Http Request Headers that will be mapped.$$ *($$String[]$$, default: `$$<none>$$`)*
$$http-gateway.mapped-response-headers$$:: $$Http Response Headers that will be mapped.$$ *($$String[]$$, default: `$$<none>$$`)*
$$http-gateway.path-pattern$$:: $$An Ant-Style pattern to determine which http requests will be captured.$$ *($$String$$, default: `$$/$$`)*
$$http-gateway.resource-location-uri$$:: $$Base URI where externalized contents will be stored.$$ *($$String$$, default: `$$file:///tmp/$$`)*
$$http-gateway.timeout$$:: $$Timeout value for the connection$$ *($$Long$$, default: `$$300000$$`)*
$$server.port$$:: $$Server HTTP port.$$ *($$Integer$$, default: `$$8080$$`)*
//end::configuration-properties[]

NOTE: Security is disabled for this application by default.
To enable it, you should use the mentioned above `http.enable-security = true` property.

== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then cd into one of the folders and build it:
```
$ ./mvnw clean package
```

== Examples

```
java -jar http-gateway-processor-kafka-2.1.0.RELEASE.jar

```



